### ISSUE TITLE
UHD build issues

### ISSUE THREAD

**Issue by alexchartier** [jvierine/ionosonde#3]
On Raspberry Pi 3B+, apt-get failed to find some dependencies:

E: Package 'libncurses5-dbg' has no installation candidate
E: Package 'libqwtplot3d-qt5-dev' has no installation candidate

Following that, cmake completed OK, but make failed as follows:

 [ 11%] Building CXX object lib/CMakeFiles/uhd.dir/convert/convert_with_neon.cpp.o
In file included from /home/pi/uhd-3.15.0.0/host/lib/convert/convert_with_neon.cpp:10:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h: In member function ‘virtual void __convert_fc32_1_sc16_item32_le_1_PRIORITY_SIMD::operator()(const input_type&, const output_type&, size_t)’:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:6740:1: error: inlining failed in call to always_inline ‘float32x4_t vdupq_n_f32(float32_t)’: target specific option mismatch
 vdupq_n_f32 (float32_t __a)
 ^~~~~~~~~~~
/home/pi/uhd-3.15.0.0/host/lib/convert/convert_with_neon.cpp:26:33: note: called from here
     float32x4_t Q0 = vdupq_n_f32(float(scale_factor));
                      ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~

**Comment by alexchartier** [comment]
Works fine on Ubuntu 18.04 with amd64
